### ISSUE TITLE
Episode Range based scraping

### ISSUE THREAD

**Issue by shivsah** [Hyperclaw79/GoGoAnime-Spider#1]

**Comment by Hyperclaw79** [comment]
@shivsah 
Since the vidstream links are not working atm, I have kept the production of the script on hold. 
It's definitely possible to incorporate range scraping. 
Thanks for the suggestion,

**Comment by Hyperclaw79** [comment]
@shivsah Successfully Implemented _Range_ based scraping. Also, if you want to download with auto quality, the script is now much faster.
